set -g @plugin "dracula/tmux"

# Black Metal Rose Color Palette
white="#c1c1c1"       # Base 05
gray="#1c1c1c"        # Base 01
dark_gray="#121212"   # Base 00
light_purple="#999900" # Base 0E (The "Rose" tint)
dark_purple="#aa3333"  # Base 03
cyan="#eeeeee"        # Base 0C
green="#888888"       # Base 0D
orange="#aaaaaa"      # Base 09
red="#5f8787"         # Base 08
purple="#999900"      # Base 0E
pink="#444444"        # Base 0F
yellow="#a8a8a8"      # Base 0A

# Override default colors
set -g @dracula-colors "
  white='$white'
  gray='$gray'
  dark_gray='$dark_gray'
  light_purple='$light_purple'
  dark_purple='$dark_purple'
  cyan='$cyan'
  green='$green'
  orange='$orange'
  red='$red'
  purple='$purple'
  pink='$pink'
  yellow='$yellow'
"

set-option -g status-position bottom

# left icon
set -g @dracula-show-left-icon "#S"
# weather
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false

set -g @dracula-time-format "%F %R"

set -g @dracula-ssh-session-max-len 20

set -g @dracula-plugins "ssh-session battery network weather time"
