set $swaylock_command 'exec ~/.config/sway/config.d/scripts/swaylock-command.sh'

# setup sway idle manager
exec_always sh ./scripts/generate-random-ascii-background.sh && swayidle -w \
    timeout 300 '$swaylock_command -f' \
    timeout 600 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep '$swaylock_command -f'

# scripts
exec_always "$scripts_dir/autotiling"

# make screen warmer during night hours
exec_always wlsunset -l 52.2 -L 21.0 -t 3500 -T 6500

# gnome keyring daemon
exec --no-startup-id /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg

# cloud drive
exec sh -c 'sleep 2 && exec ~/bin/pCloud.AppImage'

# notification daemon
exec mako
