set -g @dracula-colors "
white='{{color7}}'
gray='{{color8}}'
dark_gray='{{color0}}'
light_purple='{{color4}}'
dark_purple='{{color12}}'
cyan='{{color6}}'
green='{{color2}}'
orange='{{color9}}'
red='{{color1}}'
pink='{{color5}}'
yellow='{{color3}}'
"
